//
// filename: shaders.h
//
//   Auto-generated header file containing code from all shadersused in this
// program.  A list of the files used to generated this file can be found at
// the bottom of this file.
//
// file generated by:     glsl_to_c
//
//



#ifndef  _SHADERS_H_
# define _SHADERS_H_

struct shader_code
{
  const char* code;
  const int   size;

  shader_code( const char* c, int s ) : code(c), size(s)
  {}
};

//
// From file:  simple.v.glsl
//
const shader_code SIMPLE_v(
  "#version 450 core\n"
  "out vec4 color;\n"
  "void main()\n"
  "{\n"
  "  gl_position = vec4( 0.0, 0.0, 0.5, 1.0 );\n"
  "}\n"
  ,
  94
);


//
// From file:  simple.f.glsl
//
const shader_code SIMPLE_f(
  "#version 450 core\n"
  "out vec4 color;\n"
  "void main()\n"
  "{\n"
  "  color = vec4( 0.0, 0.8, 1.0, 1.0 );\n"
  "}\n"
  ,
  88
);



#endif /* _SHADERS_H_ */

//
// Summary of all files used for generation of this header:
//
// simple.v.glsl
// simple.f.glsl
//


